Homework2
maksimknp/2018-FS-11-Frontend-Konoplev pull request #2
Opened 2018-10-18 10:58 UTC by maksimknp

2018-10-18 16:37 UTC, martinkomitsky commented on .editorconfig
> +root = true
Очень хорошо, +

2018-10-18 16:38 UTC, martinkomitsky requested changes
Не сделано задание про `getReadableSize(100000); //"98 Кбайт"`

2018-10-18 17:19 UTC, maksimknp commented on .editorconfig
> +root = true
Это сарказм или я не понял?

2018-10-18 17:24 UTC, martinkomitsky commented on .editorconfig
> +root = true
Не понял. Мало кто думает про такие штуки

2018-10-20 18:48 UTC, martinkomitsky approved these changes

2018-10-20 18:50 UTC, martinkomitsky approved these changes

2018-10-20 18:50 UTC, merged

2018-10-20 18:50 UTC, martinkomitsky commented
10